sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: java
jdk:
  - oraclejdk8
env:
  - NODE_VERSION=7.2.0
before_install:
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sleep 3
install:
  - nvm install $NODE_VERSION
  - npm install
script:
  - nvm use $NODE_VERSION
  - npm test
cache:
  directories:
    - node_modules
