language: node_js
node_js:
  - "10"
  - "8"
services:
  - xvfb
addons:
  chrome: stable
before_install:
 - export DISPLAY=:99.0
 - sleep 3
 - npm install -g npm@latest
 - npm install -g greenkeeper-lockfile
install: npm install
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
script:
  - npm test
